### ISSUE TITLE
TypeError: lrelu() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by yangcheng001** [tadax/srgan#3]
when I run "python train.py ",I got this error:

Traceback (most recent call last):
  File "train.py", line 96, in <module>
    train()
  File "train.py", line 17, in train
    model = VGG19()
  File "/home/yc/tensorflow_samples/srgan-master_tadax/vgg19/vgg19.py", line 14, in __init__
    self.out, self.phi = self.build_model(self.x)
  File "/home/yc/tensorflow_samples/srgan-master_tadax/vgg19/vgg19.py", line 23, in build_model
    x = lrelu(x, self.trainable)
TypeError: lrelu() takes 1 positional argument but 2 were given

Was there anything that I have ignored? thank you

**Comment by tadax** [comment]
Thank you for your report. I fixed bugs wholly.
Could you try it again?

**Comment by yangcheng001** [comment]
That's great! Thank you
